name: Terraform Build
on:
  push:
    paths:
      - '**.tf'
      - '**.tfvars'
    branches:
      - master

       
jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Print Test Message
        run: |
          echo "This is a test message"
          echo "Triggered by push event"

